name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install dependencies
      run: go install -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: Build for windows
      run: GOARCH=amd64 GOOS=windows go build -o murphysec-windows-amd64.exe -v .
      
    - name: Build for linux
      run: GOARCH=amd64 GOOS=linux go build -o murphysec-linux-amd64 -v .

    - name: Build for macos amd64
      run: GOARCH=amd64 GOOS=darwin go build -o murphysec-darwin-amd64 -v .
        
    - name: Build for macos arm64
      run: GOARCH=arm64 GOOS=darwin go build -o murphysec-darwin-arm64 -v .


