name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64]
        include:
          - goos: darwin
            goarch: arm64
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install dependencies
      run: go install -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v -o out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Rename for Windows
      if: matrix.goos == 'windows'
      run: mv out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }} out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }}.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: murphysec-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        path: out/*
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure
        run: |
          echo Current Path
          pwd
          echo Show Files
          find
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            ./murphysec-darwin-amd64.zip/murphysec-darwin-amd64
            ./murphysec-linux-amd64.zip/murphysec-linux-amd64
            ./murphysec-windows-amd64.zip/murphysec-windows-amd64.exe
            ./murphysec-darwin-arm64.zip/murphysec-darwin-arm64

      
 
      
